# Site settings
title: Scott Nath
subtitle: Senior Front End Developer, IBM
email: online@scottnath.com
description: > # this means to ignore newlines until "baseurl:"
  Coding-related things by Scott Nath. Many smarts, much wizard!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://scottnath.github.io" # the base hostname & protocol for your site
twitter_username: scottnath
github_username: scottnath
linkedin_username: scottnath

exclude:
  - node_modules
  - global-assets
  - patterns
  - styles
  - lib
  - config.yml

timezone: America/New_York

# Build settings
markdown: kramdown
kramdown:
  input: GFM
