# name of the data file for individual pattern
dataFileName: 'pattern.yml'
# details on our prototyper
jekyll:
  dest: './'
# location of a library's global assets
globalAssets: './global-assets'
# location of our local patterns
localPatternsDir: './patterns'
# the github repository for this pattern library
githubrepo: scottnath.github.io
# array of pattern libraries imported via npm
# npmPatternRepos:
# templates imported into pattern lab after it is installed by composer
templates:
# configs required for various file types
fileTypes:
  css: # css files
    globalAssetsSrc: # source(s) for any css files in global assets
      - '{{ globalAssets }}/styles/css/**/*.css'
    # destination for css from global assets
    globalAssetsDest: '{{ jekyll.dest }}/css'
  fonts:
    globalAssetsSrc:
      - '{{ globalAssets }}/fonts/*'
      - '{{ globalAssets }}/fonts/**/*'
    globalAssetsDest: '{{ jekyll.dest }}/fonts'
  images:
    globalAssetsSrc:
      - '{{ globalAssets }}/images/*'
      - '{{ globalAssets }}/images/**/*'
    globalAssetsDest: '{{ jekyll.dest }}/images'
  js:
    prototyperSrcDir: '{{ jekyll.dest }}/js' # javascript directory inside source directory inside pattern lab
    globalAssetsSrc:
      - '{{ globalAssets }}/js/**/*.js'
  patterns:
    prototyperDestDir: '{{ jekyll.dest }}' # destination for patterns inside pattern lab
  sass:
    prototyperSrcDir: '{{ jekyll.dest }}/_sass' # sass directory inside source directory inside pattern lab
    prototyperSrc: '{{ jekyll.dest }}/source/css/scss/style.scss' # primary sass file in prototyper
    prototyperDestDir: '{{ jekyll.dest }}/source/css' # location for compiled css file in prototyper
    prototyperDest: '{{ jekyll.dest }}/source/css/style.css' # final compiled css file in prototyper
    globalAssetsSrc: # source of global asset's SASS file(s)
      - '!{{ globalAssets }}/styles/scss/style.scss'
      - '{{ globalAssets }}/styles/scss/**/*.scss'
    globalAssetsDest: '{{ jekyll.dest }}/source/css/scss/global-assets' # destination for global asset's SASS file(s);
    jekyllSrc:
      - '{{ jekyll.dest }}/_sass/**/*.scss'
      - '{{ jekyll.dest }}/css/main.scss'
    jekyllDest: '{{ jekyll.dest }}/css/'
# configuration variables for gulp tasks
gulpTasks:
  # cloning a pattern
  clonePattern:
    taskName: clone # the task name
  # glob/inject tasks
  fileGlobInject:
    js:
      srcFile: '{{ jekyll.dest }}/source/_meta/_01-foot.twig'
      destDir: '{{ jekyll.dest }}/source/_meta'
    sass:
      srcFile: '{{ globalAssets }}/styles/scss/style.scss'
      destDir: '{{ globalAssets }}/styles/scss'
      filesGlobalAssets:
        - '!./{{ globalAssets }}/**/style.scss'
        - './{{ globalAssets }}/**/*.scss'
      filesLocalPatterns:
        '{{ localPatternsDir }}/**/*.scss'
  # sass compilation
  gulpSass:
    dependencies:
    src: '{{ fileTypes.sass.jekyllSrc }}'
    dest: 'test'
  # pattern importing tasks
  patternImporter:
    localPatterns: # patterns in THIS pattern library
      config:
        htmlTemplateDest: '{{ fileTypes.patterns.prototyperDestDir }}' # where the html templates will go when imported
        stylesDest: '{{ fileTypes.sass.prototyperSrcDir }}/local' # where the sass/css will go when imported
        scriptsDest: '{{ fileTypes.js.prototyperSrcDir }}/local' # where the javascript will go when imported
        convertCategoryTitles: false # convert category titles - converts 'atoms' to '00-atoms' for pattern lab
        templateEngine: html
      taskName: 'patterns-import-local' # the task's name
      src:
        - './patterns/**/pattern.yml' # patterns to be imported by this task
    npmPatterns: # pattern libraries imported via NPM
      config:
        convertCategoryTitles: false
  # for replacing URLs when exporting library to github pages
  replaceUrl:
    ghPagesPrefix: '/{{ githubrepo }}'
    src:
      - '{{ jekyll.dest }}/source/**/*.json'
